### ISSUE TITLE
Log rotate should compress non-current log files

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-puppet#107]

**Comment by jewzaam** [comment]
Why?  If we keep only a subset of logs do we need to bother compressing?  Will it impact splunk?  Today we keep 50 server.log and it's rotated based on size.  I think this comes out of #108 which was initially thought to be a cause of running out of disk.  I saw it was heap dumps in the bin dir that was really using disk on at least one node (6.5GB) vs logs (<500MB).

**Comment by dcrissman** [comment]
I think Splunk keeps its own copy, but none-the-less, this ticket may be pre-mature. If log size does become an issue, we can deal with it then.
