### ISSUE TITLE
Setup the integration with external tools

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-puppet#12]
To configure the project (and sub-projects) to use: travis, coveralls.io, jenkins (triggering the proper dependencies).

**Comment by jewzaam** [comment]
Travis for lightblue-puppet: https://travis-ci.org/lightblue-platform/lightblue-puppet
Issue for coveralls: https://github.com/lightblue-platform/lightblue-puppet/issues/53
