### ISSUE TITLE
Move default location for migrator jar

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-puppet#126]
Probably somewhere under /usr/share/migrator instead of a 'jbossas' dir.  There is no jboss for migrator.

**Comment by dcrissman** [comment]
As far as I can tell, this would require two changes:
* migrator parent pom: rpm.install.basedir
* lightblue::application::migrator:jar_path

We will want to verify that the old jar is removed when the new rpm is installed.

**Comment by dcrissman** [comment]
It looks like this is already done. I am adding a simple PR to do a little pom clean up, but otherwise I think this can be closed.

https://github.com/lightblue-platform/lightblue-migrator/pull/403
