### ISSUE TITLE
Deloyment of eap6.keystore should require jboss package

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-puppet#14]
The jboss package creates the configuration dir in which the keystore is deployed.  On a first puppet run this will fail if the jks bits are executed first.

**Comment by luan-cestari** [comment]
Merged https://github.com/lightblue-platform/lightblue-puppet/pull/38  (I saw the othr PR https://github.com/lightblue-platform/lightblue-puppet/pull/37 with the same commit that was closed, bit strange ). Closing this issue
