### ISSUE TITLE
Need a way to not deploy stuff in lightblue::cacert class

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-puppet#150]
Right now this class is included in several places.  The problem is the file we are deploying is managed by another class in our internal puppet code (there's a 'base' class that ends up landing it).  Didn't catch it until now because it isn't part of the class used for the current production lightblue nodes, the problem is a different class is used in a different datacenter and it ends up also defining this file.

So, we need a way to not have this class land.  The params are all required right now.  We could do some host specific overrides in hiera or maybe a param that would turn off this feature?

Need it really soon too.

**Comment by bserdar** [comment]
Can we change the lightblue::cacert class to depend on the base cacert
class, and then insert whatever certs need to be inserted?

**Comment by jewzaam** [comment]
No, that base class is internal only.  We could move this to our internal
lightblue module, but that's not great either as there's code here that
really depends on the cert.

The code in lightblue::cacert could be updated to check if the cacert file
is already managed by puppet somewhere.  But, if the order they're
evaluated is non-deterministic then puppet runs could fail sometimes.

**Comment by paterczm** [comment]
I can work on this tomorrow if nobody can/wants to do it sooner.

**Comment by jewzaam** [comment]
@paterczm did you have a chance to look at this?
