### ISSUE TITLE
Setup rolling access logs

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-puppet#183]
Ours are taking 12gb in prod right now.. bit excessive.

**Comment by paterczm** [comment]
https://access.redhat.com/solutions/185383
http://docs.jboss.org/jbossweb/7.0.x/config/host.html

JBoss can rotate access logs, but does not have an option of deleting the old ones (like it does for server logs).

This is how servicejava solved it:

```
0 4 * * * /usr/sbin/tmpwatch -m 1424 /var/log/jbossas/standalone/default-host
```

**Comment by jewzaam** [comment]
We have this installed already.  Looking into why it's not clearing logs.
