### ISSUE TITLE
Add ability to deploy Lightblue-LDAP

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-puppet#69]
We need a way to deploy Lightblue-LDAP via puppet.

https://github.com/lightblue-platform/lightblue-ldap

**Comment by jewzaam** [comment]
This means configuration additions for the ldap bits.  Is there anything lightblue-ldap specific that needs to be done to puppet?  This should be hiera updates I think.

**Comment by dcrissman** [comment]
I believe at a minimum the datasources.json.erb will need to be modified to support LDAP.
