### ISSUE TITLE
Fixes #83: Add support for CORS configuration

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-puppet#82]
See: https://github.com/lightblue-platform/lightblue-rest/pull/86

Need to lay down a templated config file much like the other crud and metadata config files.

I can work on this tomorrow.

**Comment by dcrissman** [comment]
I see this is marked as 'ready for review', but is there a PR associated with hit?

**Comment by alechenninger** [comment]
Yep, https://github.com/lightblue-platform/lightblue-puppet/pull/83
