### ISSUE TITLE
Deploy statsd env variables

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-puppet#93]
Similar to graphite, need these env variables for statsd:
* STATSD_PREFIX
* STATSD_HOSTNAME
* STATSD_PORT

Implementation detail, the prefix we use should NOT be the same as graphite publishing.  Maybe as simple as "lightblue" will be ok, since it will be embedded within the collectd/statsd prefix for the host that exists already.

**Comment by dcrissman** [comment]
What the prefix is will be specific to the implementation.

**Comment by dcrissman** [comment]
https://github.com/lightblue-platform/lightblue-puppet/pull/94
